### ISSUE TITLE
Better backups using the save command

### ISSUE THREAD

**Issue by TheDogg** [Benjerman/Minecraft-Server-Manager#1]
Your current backup function stops the server to backup the world.  this is not a good approach when the server is in use.  There is a save command (save hold, save query and save resume) that allows the world to be backed up while the server is running.  if you could make use of that then we could backup the server every 30 mins (like realms currently do) and never have to stop the server.

The save commands are listed in the documentation that comes with the server (See Backup section) the only thing that is required is to truncate the file to the length returned by the Save Query function in order to have valid backups.

this would make the server manager usable for realm replacement.

**Comment by raykai** [comment]
Bug BDS-2733
Link: [https://bugs.mojang.com/browse/BDS-2733](https://bugs.mojang.com/browse/BDS-2733)
This bug prevents the system from copying two key world files during a backup whilst the server is running preventing regular backups. so for now yes its the best way to do a backup.

**Comment by Benjerman** [comment]
This has been added to the newest release.
